import localFont from "next/font/local";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import QueryProvider from "../ui/components/QueryProvider";

export const metadata = {
  title: "wekids",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={`antialiased`}>
        <QueryProvider>
          <div className="wrapper">{children}</div>
        </QueryProvider>
      </body>
    </html>
  );
}
